language: java
 
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
 
script:
  - mvn test -B
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
 
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    tags: true
